apiVersion: kubernetes.x1/v1beta2
kind: LdapRole
metadata:
  name: wildfly-roles
  namespace: default
spec:
  roles:
  - role: wildfly-admins
    gid: 1000005
    description: Wildfly Administrators
    users:
    - joe
    - sysadm
  - role: wildfly-users
    gid: 1000006
    description: Wildfly Users
    users:
    - joe
    - snowdog
