kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ldap-operator
  name: ldap-operator
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      deployment: ldap-operator
      app: ldap-operator
  template:
    metadata:
      labels:
        deployment: ldap-operator
        app: ldap-operator
    spec:
      serviceAccountName: ldap-operator
      containers:
      - name: ldap-operator
        image: registry.x1/j7beck/ldap-operator:1.0
        imagePullPolicy: Always
        env:
        - name: LDAP_USER
          value: "uid=root,cn=users,dc=x1"
        - name: LDAP_PASSWORD
          value: "SandTHEM"
        - name: LDAP_URL
          value: "ldap://ldap.x1"
        - name: LDAP_SEARCH_BASE
          value: "dc=x1"
        - name: QUARKUS_LOG_CONSOLE_JSON
          value: "true"
        resources:
          limits:
            memory: "640Mi"
          requests:
            memory: "512Mi"
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
